version: '3'

services:
  traefik:
    image: 'traefik:v2.10'
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.web.http.redirections.entrypoint.to=websecure'
      - '--entrypoints.web.http.redirections.entrypoint.scheme=https'
      - '--entrypoints.websecure.address=:443'
      - '--certificatesresolvers.myresolver.acme.tlschallenge=true'
      - '--certificatesresolvers.myresolver.acme.email=gassnake999@gmail.com'
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - './letsencrypt:/letsencrypt'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    networks:
      - network

  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.whoami.rule=Host(`whoami.madcodelife.com`)'
      - 'traefik.http.routers.whoami.entrypoints=websecure'
      - 'traefik.http.routers.whoami.tls.certresolver=myresolver'
    networks:
      - network

  redirect:
    image: 'nginx:latest'
    labels:
      - 'traefik.enable=true'

      # tesla
      - 'traefik.http.routers.tesla.rule=Host(`tesla.madcodelife.com`)'
      - 'traefik.http.routers.tesla.entrypoints=websecure'
      - 'traefik.http.routers.tesla.tls.certresolver=myresolver'
      - 'traefik.http.routers.tesla.middlewares=redirect-tesla'

      - 'traefik.http.middlewares.redirect-tesla.redirectregex.regex=(.)*'
      - 'traefik.http.middlewares.redirect-tesla.redirectregex.replacement=http://h.madcodelife.com:10001'
      - 'traefik.http.middlewares.redirect-tesla.redirectregex.permanent=true'

      # tesla grafana
      - 'traefik.http.routers.tesla-grafana.rule=Host(`tesla-grafana.madcodelife.com`)'
      - 'traefik.http.routers.tesla-grafana.entrypoints=websecure'
      - 'traefik.http.routers.tesla-grafana.tls.certresolver=myresolver'
      - 'traefik.http.routers.tesla-grafana.middlewares=redirect-tesla-grafana'

      - 'traefik.http.middlewares.redirect-tesla-grafana.redirectregex.regex=(.)*'
      - 'traefik.http.middlewares.redirect-tesla-grafana.redirectregex.replacement=http://h.madcodelife.com:10002'
      - 'traefik.http.middlewares.redirect-tesla-grafana.redirectregex.permanent=true'
    networks:
      - network

networks:
  network:
    driver: bridge
